stack_name: testsporesinatrapaas2-qa
environment: test
paas_environment: test

layers:
  - dns:
      - name: 'testsporesinatrapaas2.test.paas.vodalabs.com.au'
    instances:
      ami_name: <%=ami_name%>
      env:
        LOG_FILENAME: testsporesinatrapaas2-qa
